name: Build Haskell with Stack

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC with Stack
      uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Cache Stack
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Run tests
      run: stack test
