name: Build Haskell with Stack

on:
  push:
    branches: [ "master", "ci" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "ci" ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC with Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Cache Stack
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Run tests
      run: stack test

    - name: Create release artifact
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p dist
        stack install --local-bin-path dist
        zip -j dist/${{ github.event.repository.name }}-${{ github.ref_name }}.zip dist/*

    - name: Upload release to GitHub
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.zip
